# Generated by Django 4.0.6 on 2022-08-08 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresos',
            name='NombreProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.productos'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='NombreProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.productos'),
        ),
    ]
